<a href="https://colab.research.google.com/github/Theresah123/Tutorials/blob/main/Ex4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a 3×3 NumPy array with numbers from 1 to 9 using arange.

In [1]:
import numpy

In [5]:
arr = numpy.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# Find the sum, mean, and max value

In [6]:
print(arr.sum())

45


In [7]:
print(arr.mean())

5.0


In [8]:
print(arr.max())

9


In [ ]:
# Reshape it into a 1×9 array.

In [10]:
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Create two arrays and perform element-wise multiplication.

In [11]:
arr1 = [1,2,3,4,5]

In [12]:
arr2 = [3,5,2,6,7]

In [15]:
print(numpy.multiply(arr1, arr2))

[ 3 10  6 24 35]
