<a href="https://colab.research.google.com/github/Theresah123/Tutorials/blob/main/Ex5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Modules & Packages

    Create a module named math_ops.py with functions:

    add(a, b)

    subtract(a, b)

    multiply(a, b)

    divide(a, b)

    Then import and use these functions in another script.

    Create a package named shapes with:

    Module circle.py → function area(r)

    Module rectangle.py → function area(l, w)

    Then import and test both.

NumPy

    Create a 3×3 NumPy array with values from 1 to 9.

    Find:

    Sum of all elements

    Mean

    Maximum value

    Reshape it into a 1×9 array.

    Create two arrays and perform:

    Addition

    Multiplication (element-wise)

    Extract all elements greater than 5 using boolean indexing.

    Create a 2D array and calculate:

    The sum along each row (axis=1)

    The sum along each column (axis=0)

    Use NumPy to generate:

    An array of 10 random integers

    Sort them in ascending order

    Create an array from 0 to 20 with step size 2, then reshape it into 2 rows.

In [1]:
import numpy

In [7]:
arr = numpy.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.sum()

np.int64(45)

In [9]:
arr.mean()

np.float64(5.0)

In [10]:
arr.max()

np.int64(9)

In [11]:
arr.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
arr1 = numpy.array([1, 2, 5])
arr2 = numpy.array([4, 3, 6])

In [13]:
add = arr1 + arr2
add

array([ 5,  5, 11])

In [15]:
mult = arr2 *arr1
mult

array([ 4,  6, 30])

In [18]:
arr = numpy.array([2, 3, 4, 5, 6, 8, 9, 7, 10])

In [17]:
elements_greater_than_5 = arr[arr > 5]
elements_greater_than_5

array([ 6,  8,  9,  7, 10])

In [19]:
arr_2D = numpy.array([[1, 2, 3],
                      [4, 5, 6],
                      [8, 7,9]])

In [21]:
sum_rows = numpy.sum(arr_2D, axis=1)
sum_rows

array([ 6, 15, 24])

In [22]:
sum_columns = numpy.sum(arr_2D, axis=0)
sum_columns

array([13, 14, 18])

In [25]:
random_integers = numpy.random.randint(0, 100, size=10)
random_integers

array([40, 45, 66, 28, 89, 54,  6, 74, 70,  7])

In [26]:
sorted_int = numpy.sort(random_integers)
sorted_int

array([ 6,  7, 28, 40, 45, 54, 66, 70, 74, 89])

In [59]:
arr = numpy.arange(2, 21, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
reshaped = arr.reshape(2, -1)
reshaped

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

Write a program to find the largest of three numbers.

In [35]:
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))

Enter the first number: 10
Enter the second number: 40
Enter the third number: 77


In [38]:
if num3 > num2 and num3 > num1:
    print("The largest number is: ", num3)

The largest number is:  77


    Write a program to print numbers from 1 to 10 using a for loop.

    Write a program to calculate the sum of the first 5 natural numbers.

    Print a multiplication table for a given number.

    Write a program that prints all even numbers between 1 and 20.

In [39]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [41]:
total = 0
for i in range(1, 6):
    total += i
    print(total)

1
3
6
10
15


In [43]:
num = int(input("Enter a number: "))
for g in range(1, 11):
  print(f"{num} * {g} = {num * g}")

Enter a number: 2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


In [44]:
for f in range(1, 21):
    if f % 2 == 0:
        print(f)

2
4
6
8
10
12
14
16
18
20
